### ISSUE TITLE
Borrow: tests

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#126]
- [x]  Collateral and debt chains should match the user’s chain
- [x]  View all routes should not exist
- [x]  User can see its balance of available tokens (limited if no funds ofc)
- [x]  User can input any amount
- [x]  Inputting invalid amounts should show errors (same)
- [x]  Tapping max (collateral) shows max value (requires funds)
- [x]  Tapping recommended (debt) shows the right value (requires funds)
- [x]  collateral provided, borrowed value, liquidation price and current price should update accordingly
- [x] LTV Progress updated correctly
- [ ]  Overview details should also be updated and right
- [x]  Change debt chain to Optimism, available tokens should be different
- [x]  View all routes is now visible, we should show two available routes
- [x]  Slippage settings is now visible (test that the value is updated)
- [x]  Unfold fees, check that bridge fee is > 0, the value is also shown in the first row and we show the relayer fee

**Comment by brozorec** [comment]
Transform this task to test the borrow store instead of the UI.

**Comment by ferostabio** [comment]
@NikolaiYurchenko edited the issue and there's now an up to date checklist item. Not thorough in any way, but a good basic overview of the screen I think. If you find something missing, feel free to add it
