### ISSUE TITLE
LiquidationManager

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#129]
A contract that will be attributed a "LIQUIDATOR_ROLE" and thus could call "vault.liquidate()"
- should contain a list of allowed callers (keepers)
- should allow initiating a flashloan to do a liquidation
- should be able to perform a swap

**Comment by DaigaroCota** [comment]
• Should be able to liquidate an array of users, and not revert if one of the users is not liquidatable.

@pedrovalido

**Comment by pedrovalido** [comment]
Note to self: check flasher parameter input security

**Comment by pedrovalido** [comment]
after adding a test to see if 10 users are able to be liquidated and what is the gas consumption of the liquidation manager, here are the results. As discussed, the gas should be below 2m. Even the max gas is below 2m :)

![Image](https://user-images.githubusercontent.com/80268365/224064128-0dd30e65-ce32-4e48-8ba5-39332c847462.png)
