### ISSUE TITLE
Menu: responsive handling of navigation

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#188]
### Context

The mobile version and responsiveness of the menu was forgotten during first iteration. Time to improve it.

Current problems:
- can't open account popover in mobile (click on address on desktop to see)
- no integration of Account Modal (Mobile)

[Design (up to date on the 12th of dec 2022) >](https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=2745%3A45791&t=b23Efa4MFyLYUP7N-3)

See linked branch for WIP work

### Todo

- [x] define the flow of the navigation in mobile and choose how when to enable it (enable in table or table == desktop)
- [x] make it work (need to first point to be done to be defined)

### Explanations

TBD

### Related

- discovered when doing #168

**Comment by ferostar** [comment]
We can already close this one. We must improve the mobile UX, but we have already solved this issue.
