### ISSUE TITLE
Webflow FujiV2 Landing page

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#205]
I created this issue to track comments regarding the new Fuji website landing pages created in Webflow.

The latest state can be reviewed here: https://fujiv2.webflow.io/

**Comment by DaigaroCota** [comment]
Hey @Markoyw ,

I know we took some time to provide direction on this, but here is how we should identify our brand (project).

![Image](https://user-images.githubusercontent.com/32775237/211432164-a0d3fdd8-f828-4c23-854c-99e411591a90.png)

**Comment by Markoyw** [comment]
Got it, thanks for this @DaigaroCota!
