### ISSUE TITLE
Hundred as Lending Provider

### ISSUE THREAD

**Issue by pedrovalido** [Fujicracy/fuji-v2#235]

**Comment by brozorec** [comment]
should be merged after #225 and after changing the `approvedOperator` in LendingProvider

**Comment by pedrovalido** [comment]
Looks like they're having liquidity issues trying to borrow usdc. 
I dug into their contracts and the stack trace the error was throwing
<img width="1711" alt="Screenshot 2023-01-12 at 19 13 40" src="https://user-images.githubusercontent.com/80268365/212159949-85373d10-dfc8-475e-a5d0-0bebc1ba66e0.png">

1. USDC.balanceOf(address of their hUSDC) returns 0
2. hUSDC.totalCash() function returns 0 which is also an indicator they don't currently have USDC available to borrow

I've sent them a message on telegram regarding this issue.

On gnosis chain, there was also an error being thrown called "mint is paused" which was confirmed by their team on telegram the market is in fact paused.

**Comment by pedrovalido** [comment]
Update on issue above mentioned: they are not deployed on mainnet yet so it was removed from this integration. Also, they've unpaused the mint so everything is working now
