### ISSUE TITLE
General documentation

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#262]
Preparing for code4rena:

- [x] IRouter and routers derivatives -> @brozorec
- [x] IChief -> @brozorec  
- [x] IVault and derivatives, factories, vaultpermissions -> @DaigaroCota 
- [x] ISwapper -> @DaigaroCota 
- [x] ILendingProvider and derivatives, including related provider interfaces and libraries -> @pedrovalido
- [x] IFlasher and derivatives -> @pedrovalido
- [x] AddrMapper -> @pedrovalido

**Comment by brozorec** [comment]
@DaigaroCota @pedrovalido I started reviewing the comments in Chief. Plz check carefully the changes and let me know if this format works for you and what we can improve. 

Throughout the whole code base, we use different ways to comment, different **punctuation**, there are missing natspecs for some functions, etc.

After we validate the format, we MUST stick to the same one. If we fail to do so, it's only a sign of negligence and bad coding practices.

**Comment by DaigaroCota** [comment]
I reviewed and it looks ok on my side. 

The question I have now is:

- Should we all commit in the same branch ? `protocol/docs/review-code-comments`
- Should we comment in a similar fashion the internal functions? In this case I recommend we focus the comments as `@dev` instead of `@notice`. From what I recall `@notice` is intended for public\external functions.

**Comment by pedrovalido** [comment]
**Should we all commit in the same branch ? protocol/docs/review-code-comments?**
I say yes in the same branch as we all have different files do it shouldnt be a problem to do so

**Should we comment in a similar fashion the internal functions? In this case I recommend we focus the comments as @dev instead of @notice. From what I recall @notice is intended for public\external functions.**
Yes, let's do a standard for us: @notice for external functions and @dev for internal function. lmk what you think

**Comment by brozorec** [comment]
- I suggest we work on different branches and PRs to easier review each other.

- I agree on the usage of @dev and @notice, I wasn't aware of the difference in their usage.

**Comment by brozorec** [comment]
```
@param assets Amount of assets to deposit.
```
or
```
@params assets amount of assets to deposit.
```
Which one should we use? @DaigaroCota @pedrovalido

**Comment by pedrovalido** [comment]
I would say the bottom one:
`@params assets amount of assets to deposit.`

**Comment by pedrovalido** [comment]
The naming branch convention for us to work on different branches can be protocol/docs/<name-of-the-task>. The name of the task can be the name above on the list of tasks (shortened in same cases). What do you think?

**Comment by pedrovalido** [comment]
Just notices some of the comments have "." at the end. Are we adopting this for all comments?

**Comment by DaigaroCota** [comment]
> Just noticed some of the comments have "." at the end. Are we adopting this for all comments?

I suggest we do. 

>This is an example of a proper sentence.

**Comment by pedrovalido** [comment]
Also noticed some types are being used like this in the comments - { IExample }
Should we adopt this as well?

![Image](https://user-images.githubusercontent.com/80268365/214342260-fbb7bf77-43a4-45aa-9e27-1b83c5fa75f6.png)

**Comment by pedrovalido** [comment]
Note to self: 
- [ ] write AddrMapper need to be properly configured where it is fit
- [ ] custom errors
- [ ] finish sentences with "."

**Comment by brozorec** [comment]
> I would say the bottom one: `@params assets amount of assets to deposit.`

Sorry to chime in later here but I think it doesn't feel natural to read at all. Adding a "." at the end of a phrase means it's a sentence which means it has to start with a capital letter. 

I'm aware @DaigaroCota and @pedrovalido, you have already formatted many files so I suggest you don't re-format it again, but we apply it only for the new ones.

Here's my proposal on how to write it:
`@params assets Amount of assets to deposit.`

**Comment by pedrovalido** [comment]
Actually I don't think `@param assets Amount of asset to deposit `would qualify to be a sentence. I suggest we keep `@param assets amount of assets to deposit` (removing the "." and the capital letter on the amount). This is what makes the most sense to me. Let me know what you think @brozorec @DaigaroCota

**Comment by pedrovalido** [comment]
I also suggest we remove "." from the titles as they're not sentences. What do you think?

Example
`@title Hundred Lending Provider.
`
becomes
`@title Hundred Lending Provider
`

**Comment by DaigaroCota** [comment]
On my side ok, to remove "." from titles and stick to this format:
> @title Hundred Lending Provider

Also, ok to remove capitalized letters from @param statements, and period at the end. However, trying to use the param name itself as part of the statement.
> @param `assets` amount deposit
