### ISSUE TITLE
MockAddrMapper github discussion

### ISSUE THREAD

**Issue by pedrovalido** [Fujicracy/fuji-v2#263]
Add all mappings and standards used in github discussion on addr mapper

**Comment by pedrovalido** [comment]
Link to github discussion: https://github.com/Fujicracy/fuji-v2/discussions/179

**Comment by brozorec** [comment]
convert to a Wiki page

**Comment by pedrovalido** [comment]
Here is the wiki page for the documentation on the Address Mapper. It's directly in the dashboard. Although, I think I might be a good idea to create a technical folder in the future if we dig deep into the other parts of the architecture.

https://www.notion.so/Address-Mapper-52991592321c495184b12a487afb870f?pvs=4

**Comment by brozorec** [comment]
done
