### ISSUE TITLE
Lending Proivders and Assets Logos

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#283]
Hey, these are the lists of the lending providers and assets that will use at launch. Can we make sure we have their logos available in Figma and in the dedicated FE directory? @ferostar @Markoyw :pray: 

### Lending providers
1. Aave V2
2. Aave V3
3. Compound V2
4. Compound V3
5. Euler
6. Morpho
7. Hundred
8. WePiggy (WPC)
9. dForce
10. IronBank (IB)
11. Agave
12. 0vix
13. Radiant

### Assets
1. WETH
2. WBTC
3. WMATIC
4. USDC
5. USDT
6. DAI

**Comment by Markoyw** [comment]
Hey @brozorec  @ferostar 

Here's the link to the logo assets:
https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=3771%3A74579&t=6nbdpT5UuKJ9wiMB-1

**Comment by ferostar** [comment]
Thanks @Markoyw 

@brozorec my account has exporting disabled, I think it's a permissions issue.

**Comment by brozorec** [comment]
Sorry but I should've included here the list of chains as well:

- Ethereum
- Polygon
- Arbitrum
- Optimism
- Gnosis
- BNB Chain

**Comment by ferostar** [comment]
@Markoyw above was meant for you I think, we need those assets too 😅

**Comment by Markoyw** [comment]
Hey @ferostar  @brozorec 

Sure, thanks for following up on that. 

Here's the link to the network logos:
https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=3882%3A72829&t=qxH5WBkGt6eV4nEc-1

**Comment by brozorec** [comment]
done with #287 and #284
