### ISSUE TITLE
Positions page logic

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#289]
This issue ticket implements the logic to enable the positions page and connect it with real data.

**Comment by DaigaroCota** [comment]
Hey @Markoyw what is suppose to be visbile or happen when this `view` button is clicked?

![Image](https://user-images.githubusercontent.com/32775237/218589688-79504bc2-1805-4181-81c5-c74cf823dba5.png)

**Comment by Markoyw** [comment]
Hey @DaigaroCota - at the moment we are engaging in a modal pop.

Linking the Figma design below,
https://www.figma.com/file/v53wiSwcL5DYynVL0z6L4s/Fuji---Working-File-(NEW)?node-id=492%3A6035&t=ahAwwGOTS4m3XyIv-1

After having a second look at the pop up, I think it can be further improved & simplified

**Comment by DaigaroCota** [comment]
@Markoyw  need to check with you the following:

In discussion during implementation with @brozorec , we decided adding a Go-to-action when the user has no open position. Refer to how it looks. 
![image](https://user-images.githubusercontent.com/32775237/220178388-127c057a-2785-4439-aa7f-d1d83d32db63.png)

Also, as part of the original designs, when a user has an open position and has available borrowing power, the go-to-action in in the summary to `Borrow more`. 
![image](https://user-images.githubusercontent.com/32775237/220178786-5b68bdf3-a53c-4e09-b818-0ebe3cd651e8.png)

We are aware this page will be refreshed at a later staged, though, the question at hand right now is a matter of choosing the  theming properly the buttons. What do you recommend? Please advise.

![image](https://user-images.githubusercontent.com/32775237/220178951-a398c533-d30c-499a-bac7-9052ddfa68c8.png)

**Comment by Markoyw** [comment]
Here's the link to the empty state design:
https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=4373%3A89291&t=YJEceAOPcDvahHkn-1
