### ISSUE TITLE
TimeLock can increase max LTV to >100%, enabling undercollateralized loans

### ISSUE THREAD

**Issue by rokinot** [Fujicracy/fuji-v2#320]
### Affected smart contract

[BorrowingVault.sol](https://github.com/Fujicracy/fuji-v2/blob/main/packages/protocol/src/vaults/borrowing/BorrowingVault.sol#L661-L667)

### Description

The borrowing vault has functions which modify it's risk parameters, one of it's functions being `setMaxLtv()` which has a lower bound of 1%, the function however does not have any upper bound, meaning the timelock has the ability to increase the loan-to-value amount to above 100%. In the scenario where this happens, loans could be undercollateralized, making it profitable to borrow as many times as possible and leave the protocol with a terrible bad debt. Any value above 100% will cause this vulnerability.

### Attack scenario

> Assume the price of WETH is 2000 DAI
> Timelock sets the maxLtv to 110%
> Alice discovers this change, and creates a loan of 2200 DAI after depositing 1 ETH
> With their 2200 DAI, now Alice can rebuy their ETH and still profit 200 DAI
> Alternatively, they can sell their 2200 DAI for 1.1 ETH and migrate to a new address
> They repeat the process until either the protocol is drained or the max LTV is set to lower than 100%

### Recommendation

Modify the function such as a maximum LTV above 100% reverts the call, like the code snippet below. Notice that `setLiqRatio()` does not require any modification as it already maintains a strictly below LTV value.

```
  function setMaxLtv(uint256 maxLtv_) external onlyTimelock {
    if (maxLtv_ < 1e16 || maxLtv_ > 1e18) {
      revert BaseVault__setter_invalidInput();
    }
    maxLtv = maxLtv_;
    emit MaxLtvChanged(maxLtv);
  }
```

**Comment by DaigaroCota** [comment]
Issue addressed in [commit](https://github.com/Fujicracy/fuji-v2/commit/05ae22c1e354004daebe082baad74a1fd5f9fcdb#diff-53fd86bfca3c071a50a177fa63f979c742cd15e096cd00aa3c07e7d4ce94b2b9)
