### ISSUE TITLE
Positions: modal net APY

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#321]
This ticket is to address the missing implementation of the modal that explains where the net yield calculation is coming from:

![Image](https://user-images.githubusercontent.com/32775237/219541941-89067838-52e0-48b0-8b42-8747fa87ab6e.png)

**Comment by ferostar** [comment]
Component changed to



![Image](https://user-images.githubusercontent.com/501915/225117464-5dd29712-6529-4a69-b72f-f4f822270535.png)
