### ISSUE TITLE
Unchecked Chainlink's `latestRoundData` return

### ISSUE THREAD

**Issue by rotcivegaf** [Fujicracy/fuji-v2#327]
### Affected smart contract

https://github.com/Fujicracy/fuji-v2/blob/1b939ec84af137db430fc2aa1b4c6f15e5254003/packages/protocol/src/FujiOracle.sol#L113-L115

### Description

The **FujiOracle** contract uses Chainlink's `latestRoundData` API, but not check the returned data
According to the Chainlink documentation, this could lead to stale prices:

- [Historical Price data](https://docs.chain.link/docs/historical-price-data/#historical-rounds)
- [Checking Your returned answers](https://docs.chain.link/docs/faq/#how-can-i-check-if-the-answer-to-a-round-is-being-carried-over-from-a-previous-round)

The result of latestRoundData API will be used across various functions, therefore, a stale price from Chainlink can lead to loss of funds to end-users.

### Attack scenario

The **BorrowingVault** contract use this returned data to:
- [Computes max borrow amount a user can take given their `asset`](https://github.com/Fujicracy/fuji-v2/blob/1b939ec84af137db430fc2aa1b4c6f15e5254003/packages/protocol/src/vaults/borrowing/BorrowingVault.sol#L333-L350)
- [Calculate `maxWithdraw` and `maxRedeem`](https://github.com/Fujicracy/fuji-v2/blob/1b939ec84af137db430fc2aa1b4c6f15e5254003/packages/protocol/src/vaults/borrowing/BorrowingVault.sol#L352-L373)
- [GetHealthFactor](https://github.com/Fujicracy/fuji-v2/blob/1b939ec84af137db430fc2aa1b4c6f15e5254003/packages/protocol/src/vaults/borrowing/BorrowingVault.sol#L549-L563)
- [Liquidate](https://github.com/Fujicracy/fuji-v2/blob/1b939ec84af137db430fc2aa1b4c6f15e5254003/packages/protocol/src/vaults/borrowing/BorrowingVault.sol#L578-L621)

All these functions are critical, in case of the returned price is stale could lead to a big loss for users, such as early liquidation

### Recommendation

Consider adding the missing checks for stale data, for example:

```solidity
    (uint80 roundID, int256 latestPrice,, uint256 updatedAt, uint80 answeredInRound) = IAggregatorV3(usdPriceFeeds[asset]).latestRoundData();

    if (latestPrice <= 0) {
      revert FujiOracle__negativePrice(latestPrice);
    }
    if (answeredInRound < roundID) {
      revert FujiOracle__stalePrice();
    }
    if (updatedAt == 0) {
      revert FujiOracle__roundNotComplete();
    }
    if (updatedAt < block.timestamp - observationFrequency) {
      revert FujiOracle__outdatedPrice();
    }
```

**Comment by DaigaroCota** [comment]
This issue will be closed as it relates closely to #297.
