### ISSUE TITLE
Borrow: Tracking scenario

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#34]
**Meta**

- depends on #23 
- est time: 1 day
- need information on:
  - should we create some kind of documents with all  events available and their meaning ?
  - how to name each event ?
  - metadata for each event

**Tracking Scenario for this screen**

![Image](https://user-images.githubusercontent.com/65864145/187895569-d80bac56-9778-43e2-8396-92bb4e2b8b4f.png)

1. Event - Click in Borrow Tab
2. Event - Click in Chain for collateral (CApture which chains where selected most often)
3. Event - Click in Collateral (Capture which asset selected most often)
4. Event - Click in Chain for Borrowed Asset (Capture which chain gets selected most often)
5. Event - Click in Borrowed Asset (Capture which asset selected most often)
6. Event- Adjust slider, how often users manipulated the LTV slider, what is the number that users ended up with most often
7. Event - Clicks in provider lane to expand the options

Same as in the Markets page, it would be nice to add as parameters for each event which address and chain those events are being triggered from.

**Comment by ferostar** [comment]
Should we close this one @brozorec ? We need to figure out how to implement tracking with Mark, but this issue seems outdated.
