### ISSUE TITLE
Attacker can withdraw contract’s token balance

### ISSUE THREAD

**Issue by rajatbeladiya** [Fujicracy/fuji-v2#341]
### Affected smart contract:
 BaseRouter.sol
ConnextRouter.sol
SimpleRouter.sol

### Severity:
High

### Impact:
contracts funds can be lost

### Description:

Note: `BaseRouter.sol` inhereted to `ConnextRouter.sol` and `SimpleRouter.sol` so both contracts are vulnerable and here  `BaseRouter.sol` considered as `ConnextRouter.sol` and `SimpleRouter.sol`

`BaseRouter.sol` has implemented `sweepToken()` to transfer contracts token balance, but attacker stole tokens from contract.

`xBundle()` function is used to execute actions like Deposit, Borrow, Withdraw etc. 
`xBundle()` function calls `_bundleInternal()` function internally which takes `actions[]` and `args[]` from user.
args can be constructed by `amount, receiver and sender`.
	
Suppose Attacker constructed actions as `Deposit` and `args as amount = contractBalance, receiver = address(attacker) and sender = address(Alice)`

Attacker calls `xBundle()` function with this parameters

`_bundleInternal()’s` `Action.deposit` will be called

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L136-L148

here, it calls `_safePullTokenFrom()` to transfer tokens from sender => it is used to transfer tokens only if `msg.sender` is `sender` address but if `sender` and `msg.sender` is different then it will not executed and bypass the function without revert with this attacker’s `args`.

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L320-L322

after it `vault.deposit` will call and it will transfer contract’s token balance to vault as `receiver’s address`

attacker will withdraw this funds by again calling `xBundle()` function with `Withdraw action`.

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L148-L157

or user can payback using Payback action with contracts balance

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L166-L178

### Attacke scenario:
	1. `BaseContract.sol` has 100 tokens
	2. Attacker calls `xBundle()` function with `deposit` action and  and construct `args` like `Alice address as sender` , `attacker address as receiver` and `amount as contract balance` 
	3. `_safePullTokenFrom` function will bypass (because there is no revert) and `deposit()` will transfer contracts tokens to vault onbehalf of attacker ( because receiver address is attacker’s address) 
	4. Attacker will withdraw tokens using `Withdraw action` by calling `xBundle()` again.

### Recommended Mititgation Steps:
	if (sender != address(this) && (sender == owner || sender == msg.sender)) {
      		ERC20(token).safeTransferFrom(sender, address(this), amount);
    	} else {
		revert(‘not valid sender’);
	}

### code: 
https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L136-L148

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L166-L178

**Comment by DaigaroCota** [comment]
The `_safePullToken(..)` function was updated to reduce this risk. Refer to changes in [commit](https://github.com/Fujicracy/fuji-v2/commit/5200f16bc9dfdf3384827f059b7d120477a1b165).
