### ISSUE TITLE
router: anyone can move tokens onbehalf using excess erc20 approval

### ISSUE THREAD

**Issue by rajatbeladiya** [Fujicracy/fuji-v2#342]
### Affected smart contract:
BaseRouter.sol
ConnextRouter.sol
SimpleRouter.sol

### Severity:
High

### Impact:
malicious user can damage users by depositing their assets to the vault ( no profit motive ). impact can be very much bigger if attacker find a way to steal funds from vault then he will deposit other users assets without their permission to vault and stole all the funds.

### Description:

Note: `BaseRouter.sol` inhereted to `ConnextRouter.sol` and `SimpleRouter.sol` so both contracts are vulnerable and here  `BaseRouter.sol` considered as `ConnextRouter.sol` and `SimpleRouter.sol`

`xBundle()` internally called calls `_bundleInternal()` which takes `actions[]` and `args[]` from user and it is used to execute actions like Deposit, Borrow, Withdraw etc.

this attack is impacted on the users who gave more allowance to `BaseRouter.sol` while any action performing like Deposit.( e.g. MAX allowance )
	
Suppose Alice has 1000 usdc and wants to deposit 10 tokens to Fuji’s vault.
he gave MAX allowance to `BaseRouter.sol` and call `xBundle()` function with deposit action to deposit to vault.
Alice will have 990 usdc but he gave MAX allowance is remaining.

here, `_safePullTokenFrom()` is checking only `sender != address(this) && (sender == owner || sender == msg.sender)`. so attacker can deposit tokens on behalf of other users by giving `sender` and `owner` as same address.

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L312-L323

Suppose Attacker constructed actions as `Deposit` and `args as
amount = 990,
receiver = address(Alice), 
sender = address(Alice)`

Attacker calls `xBundle()` function with this parameters
`_bundleInternal()’s` `Action.deposit` will be called and deposits 990 usdc to vault on behalf of Alice without alice’s permission. 

impact can be very much bigger if, attacker find a way to stole funds from vault then he will deposit other users assets to vault and stole all the funds.

### Attacke scenario:
	1. Alice has 1000 token and want to deposit only 10 tokens.
	2. Alice approves `max` to `BaseRouter.sol`
	3. Alice calls `xBundle()` function with `deposit` action and `args` as `amount = 10`
	4.  Alice deposits `10 tokens` successfully.
	5. Attacker will call `xBundle()` with `deposit` action and construct `args` like `Alice address as sender` and `Alice address as receiver`
	6. Action.Deposit will executed successfully and deposited tokens to the vault onbehalf of Alice.

### Recommended Mitigation Steps:
add check for if user is permitted to deposit on behalf of user

### Code:
https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L137-L147

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseRouter.sol#L320

**Comment by DaigaroCota** [comment]
Change implemented in [commit](https://github.com/Fujicracy/fuji-v2/commit/5200f16bc9dfdf3384827f059b7d120477a1b165).
