### ISSUE TITLE
previewWithdraw() should be Round up

### ISSUE THREAD

**Issue by rajatbeladiya** [Fujicracy/fuji-v2#350]
### Affected smart contract:
BaseVault.sol

### Severity:
Medium

### Impact:
ERC 4626 expects the result returned from previewWithdraw function to be rounded up. here it will return a rounded down value instead of round up value. Thus, this function does not behave as expected.

### Description:

`Note:` this type of vulnerability is submitted by one user in this contest but only for `previewMint()` but it is also vulnerable to `previewWithdraw()` function that is why I am submitted separate issue. imo it should not duplicate of that issue because all the vulnerable flow should be submitted so protocol can mitigate all the vulnerabilities in safely manner.

Per EIP 4626's Security Considerations (https://eips.ethereum.org/EIPS/eip-4626)
Finally, ERC-4626 Vault implementers should be aware of the need for specific, opposing rounding directions across the different mutable and view methods, as it is considered most secure to favor the Vault itself during calculations over its users:
* If (1) it’s calculating how many shares to issue to a user for a certain amount of the underlying tokens they provide or (2) it’s determining the amount of the underlying tokens to transfer to them for returning a certain amount of shares, it should round down.
* If (1) it’s calculating the amount of shares a user has to supply to receive a given amount of the underlying tokens or (2) it’s calculating the amount of underlying tokens a user has to provide to receive a certain amount of shares, it should round up.
Thus, the result of the `previewMint()` and `previewWithdraw()` should be rounded up.

https://github.com/Fujicracy/fuji-v2/blob/50fd0b74ccee1a73a459118e50e044a2bcfacd10/packages/protocol/src/abstracts/BaseVault.sol#L275-L277

### Recommended Mitigation Steps:
Ensure that the rounding of vault's functions behave as expected. Following are the expected rounding direction for each vault function:
* previewMint(uint256 shares) - Round Up
* previewWithdraw(uint256 assets) - Round Up 
* previewRedeem(uint256 shares) - Round Down 
* previewDeposit(uint256 assets) - Round Down 
* convertToAssets(uint256 shares) - Round Down 
* convertToShares(uint256 assets) - Round Down 

`previewMint()` returns the amount of assets that would be deposited to mint specific amount of shares. Thus, the amount of assets must be rounded up, so that the vault won't be shortchanged.

`previewWithdraw()` returns the amount of shares that would be burned to withdraw specific amount of asset. Thus, the amount of shares must to be rounded up, so that the vault won't be shortchanged.

**Comment by DaigaroCota** [comment]
This issue will be closed in PR #487 .
