### ISSUE TITLE
Allowance for debt asset

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#363]
### Context
Currently, the allowance modal handles only the collateral asset that works when we deposit. It breaks when we want to pay back.

### TODOs
- [x] extend the functionalities of the allowance modal to deal with the debt asset, too, based on the `mode`: 
- when `DEPOSIT_AND_BORROW` or `DEPOSIT` -> deal with allowance for the collateral asset
- when `PAYBACK_AND_WITHDRAW` or `PAYBACK` -> deal with allowance for the debt asset
- [x] make changes to the borrow store to account for that (maybe add a param to `allow()` to differentiate between what allowance to deal with?)

**Comment by ferostar** [comment]
@brozorec doing this I realized that even if I removed the infinite limit switch, the modal's text is all about it

```ts
<Typography mt="1rem">
  To avoid having to reapprove for subsequent transactions, you could enable infinite approval.
</Typography>

<Typography mt="1rem">
  Otherwise, only the exact amount for this transaction will be allowed to be transfered from your wallet.
</Typography>
```

**Comment by ferostar** [comment]
@brozorec we also need to decide what to do with

```ts
set(
  produce((s: BorrowState) => {
    if (s.collateral.allowance.value) {
      // optimistic: we assume transaction will success and update allowance according to that
      s.collateral.allowance.value -= parseFloat(s.collateral.input)
    }
  })
)
```

That code has been commented out, but we need to deal with it.
