### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by brozorec** [Fujicracy/fuji-v2#430]
Based on @Markoyw feedback, here are some bug fixes, mainly on the UI side. 

- For more information, check the comments in Figma on each screen.
- Start a new branch from "frontend/fix/internal-v2-testing" if it's not already merged in "main".

- [x] align icons of providers: [link](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5026%3A72067&t=E3cUvlIpGzPah8FS-1)
- [x] edit tx modal according designs: [link](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5067%3A103122&t=B71VEurTgR6vhpYE-1) and [link](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5067%3A139450&t=B71VEurTgR6vhpYE-1)
- [x] edit tx modal: close button (+ handle mobile clipping)
- [x] edit tx modal: image sizes
- [x] edit tx modal: text overlapping (works with aave, compound not)
- [x] edit tx modal: add token bottom margin too big
- [x] edit tx modal: add token color
- [x] in borrow's button comp, don't show "withdrawing" etc but "processing" for all
- [x] set fixed height background in my-positions: [link](https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5026%3A72064&t=B71VEurTgR6vhpYE-1)

**Comment by ferostar** [comment]
What is the `Validate Transaction` step in the transaction modal @brozorec ? Because we just changed the bridge step to show destination data since everyone was confused about it.

**Comment by brozorec** [comment]
> What is the `Validate Transaction` step in the transaction modal @brozorec ? Because we just changed the bridge step to show destination data since everyone was confused about it.

It's just wording, we can ignore it
