### ISSUE TITLE
M-3 Vaults cannot reach their deposit cap

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#450]
### Description
Both methods of depositing assets into the vault (deposit and mint) have the following check to revert if the deposit exceeds the deposit cap:
```solidity
if (shares + totalSupply() > maxMint(receiver)) { // @audit issue
      revert BaseVault__deposit_moreThanMax();
}
```
However, due to double accounting of `totalSupply`, the vault can never reach its deposit cap.

`maxMint` is derived from `maxDeposit`, and `maxDeposit` is calculated as `depositCap - totalAssets`.

Therefore, `maxMint` calculates the number of shares the vault can mint from that point onwards, not the maximum number of shares it can mint during its lifetime. Hence, the addition of total supply in the following line is redundant and problematic: `shares + totalSupply() > maxMint(receiver)`.

Consider a deposit cap of 100 tokens. Someone makes the first deposit of 10 tokens, resulting in a total supply of 10 tokens. Now, if someone wants to deposit 89 tokens, it should ideally be allowed, but it cannot be done due to this issue.
```
Second deposit: 89
To mint: 89
Shares + totalSupply() > maxMint(receiver)
89 + 10 > 100 - 10
99 > 90
And it reverts!
```
This makes the resultant deposit cap half of the defined one. To mitigate this issue, one can still increase the deposit cap. Therefore, we classify it as a medium severity rather than high.

### Remediation
Consider removing totalSupply from shares + totalSupply() > maxMint(receiver)
check.

**Comment by DaigaroCota** [comment]
@pedrovalido , as note for the future, also consider addressing #491 in the same PR.

**Comment by pedrovalido** [comment]
I think L-1 #491 might not be necessary to fix after all as we are going to remove the deposit cap. Please refer to the comment on the PR #495 @DaigaroCota
