### ISSUE TITLE
M-4 Vaults max__ dont comply EIP-4626

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#451]
#### Case 1:
According to [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626), the `maxDeposit`, `maxWithdraw`, `maxMint`, `maxRedeem` functions must return 0 even when the corresponding actions are temporarily disabled.

However, in Fuji vaults, this is not considered and all functions would still return actual value even if vaults are paused.

Although this is not an issue for Fuji vaults, since the pause is later enforced in the code, developers building on top of Fuji vaults may expect the EIP behavior and not handle it explicitly, leading their code down an unexpected path.

#### Remediation
Consider returning 0 if vaults are paused for maxDeposit, maxWithdraw, maxMint, and maxRedeem. Please note that maxBorrow is not part of EIP-4626, but as it takes inspiration from EIP, consider returning 0 for it as well.

#### Case 2:
According to [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626#maxdeposit) , the maxDeposit must not revert. However, it will eventually revert in the case of Fuji Vaults.
```
function maxDeposit(address) public view virtual override returns (uint256) {
    return depositCap - totalAssets(); 
}
```
Total assets in vaults can increase through two means: deposits and yield. Therefore, once yield begins to accumulate, total assets could exceed the deposit cap, even if no new deposits are made.

This presents a problem for `maxDeposit` as it would underflow and revert. This could have an impact on protocols built on top of Fuji vaults, as their code assumes that `maxDeposit` will never revert.

#### Remediation
Consider adding this check before performing the subtraction.

`if (totalAssets >= depositCap) return 0 ;`

**Comment by pedrovalido** [comment]
Note to self:
Case 1 will be addressed
Case 2 will not be addressed as deposit cap will be removed.

**Comment by DaigaroCota** [comment]
Case 2 (issue when depositCap math) will not be addressed, since the team decided to proceed with Issue #528.
