### ISSUE TITLE
Borrowing issues

### ISSUE THREAD

**Issue by ferostabio** [Fujicracy/fuji-v2#469]
- [x] When entering the borrowing screen directly, vault isn't updated
- [x] When entering the borrowing screen through markets with no account, once the user connects it overrides chains
- [x] When calls to updateVault fails the user is still able to use the borrowing component. If `availableVaultsStatus` is `error` we need to disable the button and show a notification
- [ ] Take care of issues with default chains

**Comment by ferostar** [comment]
When the user enters the borrow component directly, we always show polygon by default first and then switch to the user’s chain. This causes polygon to flash for a bit and also show the warning if the user happens to have a position there. We need to get the data as soon as possible but at the same time we need to prevent showing the wrong data -we would solve it by making collateral and debt optional in the borrow.store, but we would have to change a lot of things. Any other way out, quicker, you can think of @NikolaiYurchenko @brozorec ?

**Comment by brozorec** [comment]
@ferostar Got to another case that we don't handle. Idk if it's somehow related to the points in this ticket.

The user is connected but on an unsupported network. There're no selected chains in the form. Should we add "Select network" as a placeholder?
![image](https://user-images.githubusercontent.com/9572072/233327914-1750049b-f74a-4fd4-8f82-7d84d528f705.png)

**Comment by ferostar** [comment]
> @ferostar Got to another case that we don't handle. Idk if it's somehow related to the points in this ticket.
> 
> The user is connected but on an unsupported network. There're no selected chains in the form. Should we add "Select network" as a placeholder? ![image](https://user-images.githubusercontent.com/9572072/233327914-1750049b-f74a-4fd4-8f82-7d84d528f705.png)

Great catch. Everything points to being able not to have collateral/debt, making them optional. Again, that begs more changes. Have to test and see why we get this, I'm sure the calls fail and show we get this. Could be good enough!

So yes, I would just show a text placeholder, the user can switch networks by tapping at the button at the bottom.
