### ISSUE TITLE
Frontend testing setup

### ISSUE THREAD

**Issue by ferostabio** [Fujicracy/fuji-v2#478]
- [x] Upgrade `synpress`. We're using a really outdated version (2.4.x, the latest one is 3.5.x). This change implies a small migration we need to do before doing everything else.
- [x] Remove `borrow-specs.ts` and `metamask-specs.ts`.
- [x] Add an `account-specs.ts` file (we'll likely change the name) that tests login, logout, changing account and changing chains

**Comment by ferostabio** [comment]
- Need to figure out how to get rid of the `Couldn't find tsconfig.json. tsconfig-paths will be skipped` log.
- Need to figure out how to pass `.env` variables to `Cypress.env`, otherwise we'll be repeating them
- We need to define more test cases

**Comment by ferostabio** [comment]
Tried setting the initial custom network in code instead of through an environment variable and nothing changes (makes sense looking at their code). `synpress` supports adding only one custom network to Metamask. 

Once we support L1 we'll be able to simply add a custom unsopported network to test that case. For the time being, we need to start by choosing an unsupported network directly.

But there's another, even more important issue. When we trigger the switch from our app, we get the infamous `Switch network` alert from Metamask and all subsequent tests fail. I can actually see that the network changes and the change is reflected in the app, but cypress fails to get all data.

I would then say: 

- Not to test unsopported network
- Test only one network until supporting L1 in which case we'll be able to change to a different network directly from Metamask
- Wait until Metamask takes care of the alert that breaks everything for us

Thoughts?

**Comment by NikolaiYurchenko** [comment]
Is this alert there every time? if so, we can close it in test probably?

**Comment by ferostabio** [comment]
@NikolaiYurchenko test works great, and already added a comment specifying `synpress`'s limitations and we're moving on. No plans to get stuck because of this. Anyway the latest adition ends up with the following warning:

```
It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from `cy.` in a next command line.```
