### ISSUE TITLE
L-1 Initializing deposit cap

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#491]
### Description
The deposit cap is intended to cap the exposure initially. 
However, Fuji vaults define the deposit cap as type(uint128).max during construction with the option of reducing it through the timelock. 
```
BaseVault.sol

constructor(
    address asset_,
    address chief_,
    string memory name_,
    string memory symbol_
  )
    ERC20(name_, symbol_)
    SystemAccessControl(chief_)
    VaultPermissions(name_)
  {
		 -----
    depositCap = type(uint128).max; 
    ----
  }
```
This defeats the purpose of the deposit cap, since it allows exceeding the planned deposit cap before the timelock takes effect. Therefore, we classify this issue as medium severity.

### Remediation to consider
Consider making a deposit cap a user input during construction.

**Comment by DaigaroCota** [comment]
This low impact issue should be linked to #450 .

**Comment by pedrovalido** [comment]
start the PR from #487 branch

**Comment by DaigaroCota** [comment]
Refer to rationale for decision to close this issue in #528.
