### ISSUE TITLE
UI fixes and improvements 4

### ISSUE THREAD

**Issue by NikolaiYurchenko** [Fujicracy/fuji-v2#496]
Figma link https://www.figma.com/file/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(DUP)?node-id=5539-85197&t=gZyPMzJSvbWRAfA2-0

[PR link](https://github.com/Fujicracy/fuji-v2/pull/497)

- [x] Beta banner markup
- [x] Beta banner dismiss logic ( local store with unique key + config { key, message })
- [x] Notifications icons background 
- [x] header Navigation font 
- [x] Market page tab navigation padding
- [x] Page padding consistent
- [x] Transaction status animations
- [x] Transaction modal rework
- [x] Transaction modal detailed view
- [x] Market table row hover
- [x] 404 page
- [x] 404 background
- [x] Something went wrong page
- [x] Change market table unfolded state
- [x] Add Best label for market item and rename column title from "Chain with the best rate" to "Network"
- [x] create 3rd level of unfolding
- [x] fix market row background
- [x] My position table rows change (to be finalized)
- [x] Add liquidation price tooltip
- [x] My position table row hover (to be finalized)
- [x] Unfold the first row in markets by default
- [x] transaction modal from history opened with unfolded details and without animation
- [x] transaction animation error state
- [x] Change add token button

**Comment by brozorec** [comment]
@Markoyw can you plz update us when the missing designs for this ticket are ready 🙏
