### ISSUE TITLE
Million.js

### ISSUE THREAD

**Issue by ferostabio** [Fujicracy/fuji-v2#510]
[Million.js](https://millionjs.org/) is a 1kb Virtual DOM easy to use with React. Just in case, VDOM is

```
... a programming concept where an ideal, or “virtual”, representation of a UI is kept in memory and synced with the “real” DOM by a library such as ReactDOM. This process is called reconciliation.
```

There are year-long, heated debates about wether it actually does anything or not. So let's try it. One of the main reasons to do it BTW is that loading might improve -and that's always good.

Implementing it should be rather easy, but we have do it in a particular way because of using Next.js.

Following instructions should be enough: 

https://dev.to/tobysolutions/how-to-use-millionjs-in-a-next-app-1eim

**Comment by ferostabio** [comment]
@NikolaiYurchenko already started with this (wrapped next's config). 

You ran a couple of benchmarks, please do it again now and compare.

Then try wrapping pages, more components, to see if there are improvements as well.

**Comment by brozorec** [comment]
@NikolaiYurchenko are you benchamarking with Lighthouse? What url are you using, this one https://v2-staging-dot-fuji-306908.ey.r.appspot.com/ ?

**Comment by NikolaiYurchenko** [comment]
@ferostabio local dev
