### ISSUE TITLE
Setup e2e tests

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v2#60]
**Meta**

Estimation time : 2 days

**Goal**

- [x] Setup e2e testing framework & chrome with a metamask test wallet.
- [x] Check how to interract with metamask within cypress: test suite should be able to automatically:
  - connect a user,
  - change network,
  - accept a transaction
- [ ] Put test in CI (for @brozorec )

Note: maybe cypress is not the best tool for this 🤔 Further investigation is required

**Links**

Note: these links are from my research, they may or may not help ;)

https://www.cypress.io/
https://www.npmjs.com/package/cypress-metamask ⚠️ in issues the package looks like unmaintained
https://medium.com/andamp/extending-synpress-with-additional-metamask-commands-fdc6b35a2ffc
https://github.com/synthetixio/synpress
https://playwright.dev/

**Comment by brozorec** [comment]
@doliG I suggest you leave to me "Put test in CI" as I dealt with the GH Actions in the last couple of days and I started to get a better understanding of it.

**Comment by doliG** [comment]
- blocked by https://github.com/Synthetixio/synpress/issues/414#issuecomment-1278783299
