### ISSUE TITLE
Changes SDK to replace the param `receiver` from ConnextRouter to the new `XReceiveProxy`.

### ISSUE THREAD

**Issue by DaigaroCota** [Fujicracy/fuji-v2#643]
That will require some changes in the SDK to replace the param `receiver` from ConnextRouter to the new `XReceiveProxy`. Est. time for that change: no more than 1d

_Originally posted by @brozorec in https://github.com/Fujicracy/fuji-v2/pull/639#pullrequestreview-1504975750_

**Comment by brozorec** [comment]
after checking again, it turned out that there's no need to change anything in the sdk
