### ISSUE TITLE
Borrow: Close Position

### ISSUE THREAD

**Issue by iafhurtado** [Fujicracy/fuji-v2#65]
**Meta**

- blocked by #172 
- Estimation time : 3 days (2,5 for integration + 1 for logic)

**Features**

ℹ️ An open position can be closed from any chain

When user click on "close position with one click"
Then we open a modal filled with the information about flashclose.

When user click on "sign & close"
Then we ask for signature
Then we ask to send tx
Then we display the flyout

When tx success (be careful of cross chain flash close)
Then we display notification "successfully closed position"

**How to**

Usd `sdk.previewFlashClose()` then same flow as borrow (see sdk doc)

**Comment by doliG** [comment]
Not planned for january release
