### ISSUE TITLE
Guarded launch banner

### ISSUE THREAD

**Issue by NikolaiYurchenko** [Fujicracy/fuji-v2#656]
Create and add guarded launch banner for existing betatest users

[figma link](https://www.figma.com/proto/LkNVe5ob1LjGpbGU74Hcrs/Fuji---Design-Files-(Active)?page-id=0%3A1&type=design&node-id=6837-111397&viewport=-19%2C-109%2C0.69&t=iv1nefNeHGo8BRHG-1&scaling=min-zoom&starting-point-node-id=1089%3A36898)

AC:
- [x] Text (provided by Boyan) should contain link and message
- [x] Is shown after wallet connection
- [x] Add backgroung color property to banner and show this banner with a different color provided by Mark.
- [x] Users list to match against will be provided in a csv file that should be added to gitignore
- [x] Add the guarded launch version url to `SOCIAL_URL` constant in `constants/common.ts` 
- [x] Rename all related properties from `SOCIAL_` prefix to `HELPER_` since they are clearly not just social anymore 😅 (`SOCIAL_URL`, `SOCIAL_LINKS`, `SOCIAL_MENU`, etc).
- [x] Move `HELPER_LINKS` out from constants since it won't be a constant anymore but we'll have to add the guarded launch url if needed.
- [x] Finally, If a user is in the guarded launch address list and using any other url than the guarded launch url, add the item per the above.

**Comment by ferostabio** [comment]
Added a couple of elements to the list to make sure we don't forget to do anything, thanks for creating it in the first place @NikolaiYurchenko !
